name: Regalica Notebook CI
on:
  push: { branches: ["bloc1"] }
  pull_request: { branches: ["main"] }

jobs:
  ci:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@v4
      - name: Install deps
        run: sudo apt-get update && sudo apt-get install -y jq curl ripgrep

      - name: Docker Compose up
        run: |
          docker compose -f deploy/docker/docker-compose.yml up -d --build
          # wait for backend
          for i in {1..40}; do
            curl -fsS http://localhost:8080/health/ready && break
            sleep 2
            [ $i -eq 40 ] && exit 1
          done

      - name: Smoke test
        run: bash scripts/smoke.sh
