name: Regalica Notebook CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  denylist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run quality check
        run: |
          chmod +x ./scripts/quality-check.sh
          ./scripts/quality-check.sh

  build:
    runs-on: ubuntu-latest
    needs: denylist
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Compose
        run: sudo apt-get update && sudo apt-get install -y docker-compose

      - name: Build and start services
        run: docker-compose -f deploy/docker/docker-compose.yml up -d --build

      - name: Wait for services to be healthy
        run: |
          echo "Waiting for services..."
          sleep 60 # Give services time to start

      - name: Run healthcheck
        run: |
          chmod +x ./scripts/healthcheck.sh
          ./scripts/healthcheck.sh

  e2e:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: Install frontend dependencies
        run: cd frontend && npm ci

      - name: Install Playwright browsers
        run: cd frontend && npx playwright install --with-deps

      - name: Run Playwright tests
        run: cd frontend && npm run e2e

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: frontend/playwright-report/
          retention-days: 30

  upload-proofs:
    runs-on: ubuntu-latest
    needs: [denylist, build, e2e]
    if: success()
    steps:
      - uses: actions/checkout@v4
      - name: Create dummy proof files for CI
        run: |
          mkdir -p proofs
          echo "CI run at $(date)" > proofs/ci-run.log
          echo '{"status":"ci-run-ok"}' > proofs/ci-status.json

      - name: Upload proofs artifact
        uses: actions/upload-artifact@v4
        with:
          name: proofs
          path: proofs/
          retention-days: 90

